# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kodpU0bGjo128f59g4wdj8wO2j2SiBZ1
"""

import math

def es_primo(numero):

    # 1. Manejar casos base
    if numero <= 1:
        return False
    if numero == 2:
        return True

    # Descartar rápidamente números pares > 2
    if numero % 2 == 0:
        return False

    # 2. Usar el ciclo 'for' optimizado
    # Solo necesitamos verificar divisores impares hasta la raíz cuadrada del número.
    # Se usa int(math.sqrt(numero)) para obtener la parte entera de la raíz cuadrada.
    limite = int(math.sqrt(numero))

    # El ciclo comienza en 3, e incrementa de 2 en 2 (solo impares) hasta el límite.
    for i in range(3, limite + 1, 2):
        # Si el número es divisible por 'i', no es primo.
        if numero % i == 0:
            return False

    # Si no se encontró ningún divisor, el número es primo.
    return True

try:
    # Pedir la entrada
    entrada = input("Ingresa un número entero positivo: ")
    numero_ingresado = int(entrada)

    # Mostrar el resultado
    if es_primo(numero_ingresado):
        print(f"\n✅ El número *{numero_ingresado}* SÍ es un número primo.")
    else:
        print(f"\n❌ El número * {numero_ingresado}* NO es un número primo.")

except ValueError:
    print("\nError: Por favor, ingresa un número entero válido.")