# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnoI086bs18jG1MQoWWwPFx1OOaRdEkf
"""

def calcular_sueldo_final():
    """Calcula el sueldo semanal con jornada normal de 48h, 2h a 1.5x y el resto a 2.0x."""

    # --- Constantes ---
    HORAS_NORMALES_MAX = 48
    LIMITE_EXTRA_15 = 2  # Solo 2 horas extras a 1.5x (horas 49 y 50)
    HORAS_LIMITE_TOTAL = HORAS_NORMALES_MAX + LIMITE_EXTRA_15  # 50 horas
    TARIFA_NORMAL = 50.00  # Tarifa por hora

    # --- Entrada de Datos y Manejo de Errores ---
    print("--- Calculadora de Sueldo Semanal (Ajuste Final) ---")
    try:
        horas = float(input("Ingrese el total de horas trabajadas: "))
    except ValueError:
        print("Entrada inválida. Debe ser un número.")
        return

    sueldo = 0.0

    # --- Lógica de Cálculo (if-elif-else) ---

    # Caso 1: Horas de 51 en adelante (Máximo pago)
    if horas > HORAS_LIMITE_TOTAL: # horas > 50

        # Cálculo de los 3 componentes del pago:
        pago_extra_20 = (horas - HORAS_LIMITE_TOTAL) * (TARIFA_NORMAL * 2.0)
        pago_extra_15 = LIMITE_EXTRA_15 * (TARIFA_NORMAL * 1.5)
        pago_normal = HORAS_NORMALES_MAX * TARIFA_NORMAL

        sueldo = pago_normal + pago_extra_15 + pago_extra_20

    # Caso 2: Horas entre 49 y 50 (Solo 1.5x)
    elif horas > HORAS_NORMALES_MAX: # 49 o 50 horas

        # El resto de las horas (hasta 2) se paga a 1.5x
        horas_extra_15 = horas - HORAS_NORMALES_MAX
        pago_extra_15 = horas_extra_15 * (TARIFA_NORMAL * 1.5)
        pago_normal = HORAS_NORMALES_MAX * TARIFA_NORMAL

        sueldo = pago_normal + pago_extra_15

    # Caso 3: 48 horas o menos (Solo pago normal)
    else:
        sueldo = horas * TARIFA_NORMAL

    # --- Salida de Resultados ---
    print("\n--- Resumen de Sueldo ---")
    print(f"Horas Trabajadas: {horas:.2f}")
    print(f"Tarifa Base: S/.{TARIFA_NORMAL:.2f}/hora")
    print(f"SUELDO TOTAL: \t\tS/.{sueldo:.2f}")

# Ejecutar la función
calcular_sueldo_final()